name: Upload release assets

on:
  release:
    types:
      - created

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.x'

      - name: Build
        run: |
          go build -ldflags "-s -w" -o marcli-linux-amd64 ./cmd/marcli
          GOOS=darwin go build -ldflags "-s -w" -o marcli-macos-amd64 ./cmd/marcli
          GOOS=windows go build -ldflags "-s -w" -o marcli-windows-amd64.exe ./cmd/marcli

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: marcli*
